import type { RtlComponentRegistryEntry, RtlContractType, RtlTestLevel } from "./rtl-contract-types";

function entry(
  path: string,
  contract: RtlContractType,
  testLevel: RtlTestLevel,
  notes: string
): RtlComponentRegistryEntry {
  return { path, contract, testLevel, notes };
}

export const rtlComponentRegistry: RtlComponentRegistryEntry[] = [
  entry("components/LoadingScreen.tsx", "feedback", "source", "Centered loading surface; copy direction follows cached language."),
  entry("components/SearchCommand.tsx", "overlay", "playwright", "Search modal rows and form chrome mirror; result content can keep its natural language direction."),
  entry("components/achievements/AchievementBadge.tsx", "button", "source", "Badge/icon row mirrors when placed in RTL containers."),
  entry("components/achievements/AchievementGrid.tsx", "progress-chart", "source", "Grid order mirrors while badge art remains unmirrored."),
  entry("components/achievements/AchievementProgressBar.tsx", "progress-chart", "source", "Fill direction is explicit and follows settings RTL state."),
  entry("components/achievements/AchievementUnlockToast.tsx", "feedback", "source", "Toast content mirrors; achievement art stays neutral."),
  entry("components/achievements/PublicBadgesGrid.tsx", "progress-chart", "source", "Public badge grid mirrors visual order."),
  entry("components/auth/AuthScreenShell.tsx", "app-shell", "rntl", "Auth chrome mirrors; logo and decorative artwork do not mirror."),
  entry("components/auth/OAuthButtons.tsx", "button", "playwright", "Provider button row mirrors; provider logos remain unmirrored."),
  entry("components/flashcards/DeckCardsSheet.tsx", "overlay", "source", "Deck table sheet mirrors rows and actions; card text keeps natural direction."),
  entry("components/flashcards/DeckReviewSettingsSheet.tsx", "overlay", "source", "Review settings controls mirror inside sheet chrome."),
  entry("components/flashcards/Qcf2AyahText.tsx", "quran-text", "source", "QCF glyph text keeps Quran layout invariants and is never horizontally mirrored."),
  entry("components/flashcards/SmartDeckFilterSheet.tsx", "overlay", "source", "Filter sheet controls and list rows mirror; Quran labels keep natural direction."),
  entry("components/mushaf/AyahBlock.tsx", "mushaf-reading", "source", "Controls mirror while Quran word layout keeps direction:ltr plus row-reverse."),
  entry("components/mushaf/AyahDetailModal.tsx", "overlay", "playwright", "Detail overlay chrome and tabs mirror; Quran text remains unflipped."),
  entry("components/mushaf/BookmarksSheet.tsx", "overlay", "playwright", "Bookmark rows and sheet actions mirror."),
  entry("components/mushaf/FocusModeControls.tsx", "mushaf-reading", "source", "Reader controls mirror; progress geometry needs explicit RTL treatment."),
  entry("components/mushaf/FontSizeControl.tsx", "mushaf-reading", "rntl", "Font-size stepper order should mirror when direction-aware coverage is added."),
  entry("components/mushaf/GoToNavigator.tsx", "overlay", "playwright", "Surah/juz/page navigation rows and search chrome mirror."),
  entry("components/mushaf/HifzControls.tsx", "mushaf-reading", "source", "Reveal/hide controls mirror around fixed Quran content."),
  entry("components/mushaf/JuzNameText.tsx", "quran-text", "rntl", "Juz glyph text keeps its own writing direction."),
  entry("components/mushaf/MushafIndicator.tsx", "mushaf-reading", "rntl", "Printed-Mushaf style side labels mirror logically."),
  entry("components/mushaf/MushafPage.tsx", "quran-text", "source", "Page Quran word layout uses direction:ltr plus row-reverse; never scaleX mirrored."),
  entry("components/mushaf/MushafSlider.tsx", "mushaf-reading", "playwright", "Page slider/navigation direction needs rendered interaction checks."),
  entry("components/mushaf/PageMushaf.tsx", "mushaf-reading", "source", "Page reader controls mirror while page content and fonts stay unflipped."),
  entry("components/mushaf/PageViewNavigationSheet.tsx", "overlay", "source", "Page-view menu uses measured coordinates; internal rows mirror."),
  entry("components/mushaf/ReadingSettingsSheet.tsx", "overlay", "source", "Reader settings sheet rows and controls mirror."),
  entry("components/mushaf/RecitationRangeSheet.tsx", "overlay", "playwright", "Range controls mirror inside audio sheet."),
  entry("components/mushaf/SelectionActionBar.tsx", "mushaf-reading", "source", "Selection actions mirror; selected Quran content remains natural."),
  entry("components/mushaf/SurahHeader.tsx", "mushaf-reading", "source", "Header chrome mirrors; surah-name glyph art remains unmirrored."),
  entry("components/mushaf/SurahInfoModal.tsx", "overlay", "playwright", "Surah metadata overlay and actions mirror."),
  entry("components/mushaf/WebSelectionMenu.tsx", "overlay", "source", "Web selection menu uses measured coordinates; action ordering mirrors."),
  entry("components/mushaf/WordDetailSheet.tsx", "overlay", "playwright", "Word detail sheet chrome and tabs mirror; word glyphs remain natural."),
  entry("components/mushaf/WordToken.tsx", "quran-text", "source", "Token content keeps Quran order; interaction chrome mirrors around it."),
  entry("components/mushaf/WordTooltip.tsx", "mushaf-reading", "source", "Tooltip chrome mirrors while token text keeps natural direction."),
  entry("components/mushaf/ayah-tabs/HadithTab.tsx", "tab-segmented", "source", "Ayah tab content mirrors list rows and keeps sourced text natural."),
  entry("components/mushaf/word-tabs/IrabTab.tsx", "tab-segmented", "source", "Arabic grammar content stays RTL; surrounding tab layout mirrors."),
  entry("components/mushaf/word-tabs/MeaningTab.tsx", "tab-segmented", "source", "Arabic meaning content stays RTL; controls mirror."),
  entry("components/mushaf/word-tabs/OccurrencesTab.tsx", "tab-segmented", "source", "Occurrences list rows mirror and Quran snippets stay natural."),
  entry("components/mushaf/word-tabs/QiraatTab.tsx", "tab-segmented", "source", "Placeholder/content rows mirror; Arabic copy stays RTL."),
  entry("components/mushaf/word-tabs/TajweedTab.tsx", "tab-segmented", "source", "Tajweed labels and rows mirror without altering Quran glyphs."),
  entry("components/mushaf/word-tabs/TasreefTab.tsx", "tab-segmented", "source", "Morphology rows mirror while Arabic text stays RTL."),
  entry("components/notes/PrivateNoteSheet.tsx", "overlay", "source", "Note editor sheet chrome and actions mirror."),
  entry("components/notes/PrivateNotesSection.tsx", "card", "source", "Note rows and actions mirror; note text can use natural direction."),
  entry("components/profile/ProfileAvatar.tsx", "direction-neutral", "source", "Avatar image/fallback is not direction-dependent."),
  entry("components/profile/ProfileIdentity.tsx", "card", "source", "Identity row mirrors avatar, text, and actions."),
  entry("components/profile/ProfileModalContent.tsx", "overlay", "playwright", "Profile modal tabs, forms, stats, and rows mirror."),
  entry("components/profile/ProfileNotesManager.tsx", "overlay", "source", "Notes manager rows and sheet chrome mirror."),
  entry("components/profile/ProfileStatCard.tsx", "card", "source", "Stat card text aligns start and row order mirrors when applicable."),
  entry("components/progress/ActivityHeatmap.tsx", "progress-chart", "source", "Heatmap geometry is coordinate based; labels and surrounding layout need explicit RTL decisions."),
  entry("components/progress/DefaultDeckProgressChart.tsx", "progress-chart", "source", "Chart layout does not silently reverse chronology."),
  entry("components/progress/SurahProgressList.tsx", "progress-chart", "source", "List rows mirror while Quran/surah labels keep natural direction."),
  entry("components/public/PublicPage.tsx", "app-shell", "source", "Public content shell follows cached language direction."),
  entry("components/reflection-journey/JourneyAyahCard.tsx", "card", "source", "Journey card chrome mirrors; Quran content remains unflipped."),
  entry("components/reflections/CommentsSheet.tsx", "overlay", "playwright", "Comments sheet rows, composer, and actions mirror."),
  entry("components/reflections/ReflectionCard.tsx", "card", "source", "Author/action rows mirror; reflection text can use natural direction."),
  entry("components/reflections/ReflectionsSection.tsx", "card", "source", "Inline reflection section rows and actions mirror."),
  entry("components/reflections/WriteReflectionSheet.tsx", "overlay", "playwright", "Composer sheet chrome and actions mirror; text input can auto-direct."),
  entry("components/settings/ReciterPicker.tsx", "picker-menu", "source", "Picker rows and selected-state affordances mirror."),
  entry("components/settings/TafsirSourcePicker.tsx", "picker-menu", "source", "Tafsir picker rows and selected-state affordances mirror."),
  entry("components/settings/TranslationLanguagePicker.tsx", "picker-menu", "source", "Language picker rows and selected-state affordances mirror."),
  entry("components/ui/AppNavigation.tsx", "app-shell", "source", "Sidebar and bottom nav order/active affordances mirror."),
  entry("components/ui/AuthGate.tsx", "direction-neutral", "source", "Gate state is mostly centered/neutral; CTA row should inherit direction."),
  entry("components/ui/Button.tsx", "button", "rntl", "Icon/text order uses logical row direction."),
  entry("components/ui/Card.tsx", "card", "source", "Container is direction-neutral; child rows own mirroring."),
  entry("components/ui/ConfirmDialog.tsx", "overlay", "rntl", "Dialog title, close, and action row mirror."),
  entry("components/ui/DropdownMenu.tsx", "picker-menu", "source", "Menu item rows mirror; measured popup coordinates are viewport based."),
  entry("components/ui/EmptyState.tsx", "feedback", "source", "Centered empty state is direction-neutral unless action row is added."),
  entry("components/ui/ErrorBoundary.tsx", "feedback", "source", "Fallback actions should align logically if expanded."),
  entry("components/ui/Field.tsx", "form-field", "rntl", "Labels and messages align to start."),
  entry("components/ui/FormTextField.tsx", "form-field", "rntl", "Form wrapper passes direction to field and input chrome."),
  entry("components/ui/Input.tsx", "form-field", "rntl", "Text aligns start and icon slots mirror."),
  entry("components/ui/MirroredRow.tsx", "app-shell", "rntl", "Shared row primitives force physical row order to mirror while keeping ambient direction stable."),
  entry("components/ui/OfflineBanner.tsx", "feedback", "source", "Full-width banner is centered; action/close order mirrors when present."),
  entry("components/ui/Progress.tsx", "progress-chart", "rntl", "Fill direction is explicit and follows the active UI direction."),
  entry("components/ui/ResponsiveOverlay.tsx", "overlay", "rntl", "Overlay chrome, header, and footer action order mirror."),
  entry("components/ui/ScreenContent.tsx", "app-shell", "source", "Content gutters and sidebar offsets use direction-aware padding."),
  entry("components/ui/Sheet.tsx", "overlay", "source", "Legacy bottom sheet is position-neutral; internal content owns mirroring."),
  entry("components/ui/Skeleton.tsx", "feedback", "source", "Skeleton row shapes mirror where layout rows are directional."),
  entry("components/ui/Switch.tsx", "form-field", "source", "Thumb coordinate is internal control geometry."),
  entry("components/ui/SyncIndicator.tsx", "feedback", "source", "Status badge is icon-local and direction-neutral."),
  entry("components/ui/Text.tsx", "form-field", "rntl", "Generic text aligns to logical start by default."),
  entry("components/ui/Toast.tsx", "feedback", "source", "Centered toast is position-neutral; action order mirrors when present."),
  entry("components/ui/ToggleGroup.tsx", "tab-segmented", "rntl", "Segment order and active item placement mirror."),
  entry("components/zayt/ZaytRivePreview.native.tsx", "media-preview", "source", "Native animation asset is not mirrored by default."),
  entry("components/zayt/ZaytRivePreview.tsx", "media-preview", "source", "Shared preview wrapper keeps artwork unmirrored."),
  entry("components/zayt/ZaytRivePreview.web.tsx", "media-preview", "source", "Web Rive/canvas coordinates are asset-local, not UI layout."),
];

export const rtlComponentRegistryByPath = Object.fromEntries(
  rtlComponentRegistry.map((item) => [item.path, item])
) as Record<string, RtlComponentRegistryEntry>;
